# Generated by Django 2.2.8 on 2019-12-12 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='task_points',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
