# Generated by Django 2.2.8 on 2019-12-16 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_task_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='shop_staff',
            field=models.BooleanField(default=False),
        ),
    ]
