# Generated by Django 3.0 on 2019-12-20 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tasks',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tasks',
            name='priority',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='title',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='TaskCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('order', models.IntegerField(default=0)),
                ('tasks', models.ManyToManyField(to='tasks.Tasks')),
            ],
        ),
    ]
