# Generated by Django 3.0 on 2019-12-22 20:53

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0002_auto_20191220_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='progress',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='tasks',
            name='status',
            field=models.IntegerField(choices=[(0, 'New'), (1, 'In Progress'), (2, 'On Hold'), (3, 'Completed')], default=0),
        ),
        migrations.AddField(
            model_name='tasks',
            name='sub_tasks',
            field=models.ManyToManyField(related_name='_tasks_sub_tasks_+', to='tasks.Tasks'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='assigned_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delegated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='TaskComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateField(auto_now_add=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_comments', to=settings.AUTH_USER_MODEL)),
                ('sub_comments', models.ManyToManyField(related_name='_taskcomments_sub_comments_+', to='tasks.TaskComments')),
            ],
        ),
    ]
