# Generated by Django 3.0 on 2019-12-22 21:22

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0003_auto_20191222_2053'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_due', models.DateField()),
                ('order', models.IntegerField(default=0)),
                ('points', models.IntegerField(default=0)),
                ('priority', models.IntegerField(default=0)),
                ('status', models.IntegerField(choices=[(0, 'New'), (1, 'In Progress'), (2, 'On Hold'), (3, 'Completed')], default=0)),
                ('title', models.CharField(max_length=200)),
                ('_progress', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delegated', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('sub_tasks', models.ManyToManyField(related_name='_task_sub_tasks_+', to='tasks.Task')),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.DeleteModel(
            name='Tasks',
        ),
        migrations.AlterField(
            model_name='taskcategory',
            name='tasks',
            field=models.ManyToManyField(to='tasks.Task'),
        ),
    ]
